<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@savvycube.com so we can send you a copy immediately.
 *
 * @category   SavvyCube
 * @package    SavvyCube_Connector
 * @copyright  Copyright (c) 2017 SavvyCube
 * SavvyCube is a trademark of Webtex Solutions, LLC
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$quote = Mage::getModel('checkout/cart')->getQuote();
$quoteAlreadyTracked = Mage::getSingleton('core/session')
    ->getData('wCube_track_' . $quote->getId());
$_helper = $this->helper('googleanalytics');
?>
<?php if (!$quoteAlreadyTracked && $quote->getId() && !$this->helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
<?php
Mage::getSingleton('core/session')->setData('wCube_track_' . $quote->getId(), true);
?>
    <?php if($_helper->isUseUniversalAnalytics()): ?>
        <script type="text/javascript">
        //<![CDATA[
            (function(){ga('send', 'event', 'wCube', 'quote', <?php echo "'" . $quote->getId() .  "'"; ?>);})()

        //]]>
        </script>
    <?php else: ?>
        <script type="text/javascript">
        //<![CDATA[
            var _gaq = _gaq || [];
            _gaq.push(['_trackEvent', 'wCube', 'quote', <?php echo "'" . $quote->getId() .  "'"; ?>]);
        //]]>
        </script>
    <?php endif; ?>
<?php endif; ?>
